language: cpp
os: osx

env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release

script:
  - mkdir Mac-Build
  - cd Mac-Build
  - cmake -DCMAKE_BUILD_TYPE="${CONFIGURATION}" ..
  - make

deploy:
  provider: releases
  file: client.dylib
  skip_cleanup: true
  draft: true
  on:
    tags: true
    condition: $CONFIGURATION = Release
  api_key:
    secure: "GITHUB OAUTH TOKEN"
